name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          openjdk-11-jdk \
          unzip \
          zlib1g-dev \
          libncurses6 \
          libstdc++6 \
          libffi-dev \
          libssl-dev \
          git \
          wget \
          curl \
          lzip \
          autoconf \
          build-essential

        pip install --upgrade pip
        pip install buildozer cython

    - name: Set Android environment variables
      run: |
        echo "export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Install Android SDK components (estáveis)
      run: |
        yes | $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2" || true

    - name: Accept Android SDK licenses
      run: yes | $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses || true

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: habilitacaoapp-apk
        path: bin/*.apk
