name: Build APK (python-for-android)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build with python-for-android image
      run: |
        docker run --rm \
          -v "${{ github.workspace }}":/home/user/hostcwd \
          -w /home/user/hostcwd \
          gabrieldemarmiesse/python-for-android \
          buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: habilitacaoapp-apk
        path: bin/*.apk
